// Code generated by ogen, DO NOT EDIT.

package api

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

type Email string

type GetUsersOK struct {
	// Total number of pages available for the user list.
	TotalPages int `json:"totalPages"`
}

// GetTotalPages returns the value of TotalPages.
func (s *GetUsersOK) GetTotalPages() int {
	return s.TotalPages
}

// SetTotalPages sets the value of TotalPages.
func (s *GetUsersOK) SetTotalPages(val int) {
	s.TotalPages = val
}

// GoogleAuthInternalServerError is response for GoogleAuth operation.
type GoogleAuthInternalServerError struct{}

func (*GoogleAuthInternalServerError) googleAuthRes() {}

// GoogleAuthOK is response for GoogleAuth operation.
type GoogleAuthOK struct {
	SetCookie string
}

// GetSetCookie returns the value of SetCookie.
func (s *GoogleAuthOK) GetSetCookie() string {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *GoogleAuthOK) SetSetCookie(val string) {
	s.SetCookie = val
}

func (*GoogleAuthOK) googleAuthRes() {}

type ImageURL string

type Name string

// Request to register or log in a user using a Google JWT token and user information.
// Ref: #/components/schemas/SignInRequest
type SignInRequest struct {
	Email    Email    `json:"email"`
	Name     Name     `json:"name"`
	ImageURL ImageURL `json:"imageURL"`
	// Google JWT token provided after Google authentication.
	Token string `json:"token"`
}

// GetEmail returns the value of Email.
func (s *SignInRequest) GetEmail() Email {
	return s.Email
}

// GetName returns the value of Name.
func (s *SignInRequest) GetName() Name {
	return s.Name
}

// GetImageURL returns the value of ImageURL.
func (s *SignInRequest) GetImageURL() ImageURL {
	return s.ImageURL
}

// GetToken returns the value of Token.
func (s *SignInRequest) GetToken() string {
	return s.Token
}

// SetEmail sets the value of Email.
func (s *SignInRequest) SetEmail(val Email) {
	s.Email = val
}

// SetName sets the value of Name.
func (s *SignInRequest) SetName(val Name) {
	s.Name = val
}

// SetImageURL sets the value of ImageURL.
func (s *SignInRequest) SetImageURL(val ImageURL) {
	s.ImageURL = val
}

// SetToken sets the value of Token.
func (s *SignInRequest) SetToken(val string) {
	s.Token = val
}

type Unauthorized struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Unauthorized) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Unauthorized) SetMessage(val string) {
	s.Message = val
}

func (*Unauthorized) googleAuthRes() {}
