// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetUsers implements GetUsers operation.
//
// Retrieve a paginated list of users using limit and offset for pagination.
//
// GET /users
func (UnimplementedHandler) GetUsers(ctx context.Context) (r *GetUsersOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GoogleAuth implements googleAuth operation.
//
// Validates a Google JWT token sent from the frontend, retrieves user information, and  registers a
// new user or logs in an existing user based on token data.
//
// POST /auth/google
func (UnimplementedHandler) GoogleAuth(ctx context.Context, req *SignInRequest) (r GoogleAuthRes, _ error) {
	return r, ht.ErrNotImplemented
}
