// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package rdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64
	Email     string
	Name      string
	ImageUrl  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
